### ISSUE TITLE
Players not being listed

### ISSUE THREAD

**Issue by aftershock9** [hunterjm/futgui#12]
I came across a scenario whereby my tradepile was maxxed out, but none of the players bought were being listed. As a result, internal server (500) started cropping up after leaving it running overnight. Information:

Autobuyer version: 0.5.0

No players in tradepile initially. I added 3 players to autobuy (Wilshere, Son, N'jie).

Set the settings to the following:

RPM: 20
Min Credits: 1000
Max Players: 70

I had check the auto pricing to, 75; 95; 100.

When I looked in the morning, I had bought 70 players, but none of them had been listed. Any ideas?

**Comment by hunterjm** [comment]
So was your tradepile maxed out, or your watchlist?  They have the same limit, and you would get 500 errors if you try to bid on something, but your watchlist was full.  If it happens again, copy the entire AB log that's on the screen and take a look if you got 500 errors only after the watchlist was full, or if you got them when it tried to list players as well.

Also, just an FYI, Max Players is the number of an individual player you are willing to have listed at once and not the maximum number of cards you can trade.  For example, if the price of Son drops 20% after the AB last checked prices, if you had it set to 10, it would only buy 10 Sons.  It helps limit your losses in the event of a market crash.

**Comment by aftershock9** [comment]
On the Fifa web app - my transfer pile was maxxed out when I looked in the morning i.e. I had bought 70 odds players and had 30 players that my bids weren't successful which is weird because I only the 70 tradepile limit currently. None of the players bought, were listed however. on the autobuyer, the log started to show 500 internal server.

Re - the FYI, thanks wasn't aware of it functioning that way. Whats your recommendation to set it to? 20?

**Comment by hunterjm** [comment]
Let me know if it happens again on v0.6.0.  The only time I have players left in my watchlist is when there are some that I already bid on, but did not yet win before the AB stops bidding (whether because a temporary ban, or I stop it myself).

As for what to set max players to, it is all based on your appetite for risk.  High risk, high number (more players bought at once), low risk, low number (limits the amount of a single type of card you can have).

I personally keep it at 5 when testing new features (which is always since I am still in active development).  Obviously that is too low if you want to make a big profit.

Before I implemented that feature, I got stuck with ~100 Fellainis that took me 3 days to sell for a 15k loss (total loss of 60k since I was averaging 15k a night and lost 3 additional nights of bidding).

**Comment by aftershock9** [comment]
Cool - will keep you posted, if this does happen again.

Thanks again for the info on the max players - its good to know :).

**Comment by aftershock9** [comment]
![fut](https://cloud.githubusercontent.com/assets/6708705/11349729/5a680858-9236-11e5-92fd-1c0da028a24b.png)

I came across this issue again - I updated using v0.6.0 and it seems that the transfer pile is not being cleared for when bids are not successful. Also, it seems to only be bidding on Wilshere and not any of the other players. My assumption is that I've set it to 5 so it will continue to bid on wilshere until 5 wilsheres have been bought until it moves onto the next player?

**Comment by hunterjm** [comment]
That is correct.  I think I'll update it to only have 3x Max Player active bids as well, because that's a lot of Wilshires.  Anything that is green without a grey background is still being actively bid on, so your tradepile won't clear out until the background turns grey.

Also, what happens if you pick players in the 1-2k range?  It may just be because it is bidding on so many Wilshires that your watchlist is maxed out and it looses track.

**Comment by aftershock9** [comment]
So I did more investigation into this - it seems that even though the log is stating that its bidding only on wilshere but if i look at transfer targets page on webapp, lots of sons and funes mori have been bidded on (based on above screenshot), but the expired transfer targets or successful transfer targets haven't been cleared or listed respectively. When looking at the log, it does say its updating the watch list (i'm assuming web app transfer targets) but not clearing expired targets or listing players.

Tonight I will look to pick players in the 1-2k range and provide you with an update.

Thanks :)

**Comment by aftershock9** [comment]
Similar issue happening again:

v0.6.2 beta.
Players: price range from 2k to 5k, all silvers (clinton njie, mahrez, yedlin, beasley).

Players were bought but not being listed and transfer targets (webapp) not being cleared. See below for the log file of the errors that were being outputted. Hopefully this might give you something to work with.

See below for the log file of the messages that the fifa
![fut](https://cloud.githubusercontent.com/assets/6708705/11408791/182d256a-93c4-11e5-96fe-25bc4ee67533.png)

**Comment by hunterjm** [comment]
Perfect.  It looks like the request for getting card info is failing and the exception is not being handled properly.  Would you mind uploading or emailing me your player list?  You can find it in `C:\Users\{YourName}\.config\futgui\players.json`.  My email address is my username at @gmail.com

**Comment by hunterjm** [comment]
PR in to base library to fix this issue.  Track progress at https://github.com/oczkers/fut/pull/174.

**Comment by hunterjm** [comment]
PR has been merged.  I'll release a new version today (or tomorrow) and we will see if that fixes it.  Going to do a couple tests locally first.

**Comment by hunterjm** [comment]
Issue should be fixed in [v0.7.0](https://github.com/hunterjm/futgui/releases/tag/v0.7.0-beta).  Please re-open if it does not solve your issue.

**Comment by aftershock9** [comment]
Been running it for the past 2 hours and so far no issues. This is great stuff Jason! Thank you :)
