### ISSUE TITLE
Question about bot

### ISSUE THREAD

**Issue by Mglt-b** [hunterjm/futgui#123]
Hello,

Is the bot still under development? I see that you are working on a similar project?
What project have to follow?
Are you still update it?

Thank you

**Comment by hunterjm** [comment]
I plan on updating it if it breaks, but am not planning any new features. All the enhancements recommended here will be applied to my other project, 2which will also be free to use.

I'm moving over because of the technologies. I don't know Python very well and this boy is my first and only python project. It will be much easier for me to make updates on the new one.

**Comment by Mglt-b** [comment]
Hello, thank you for the answer.
@hunterjm 
The other projet will soon be ready?

How we can test it ?
