### ISSUE TITLE
Suggestion: Allow removal of players from list..

### ISSUE THREAD

**Issue by ghost** [hunterjm/futgui#148]
Seems pretty..basic..

**Comment by hunterjm** [comment]
1) snark won't get you anywhere in life.
2) You are using software that somebody spent a lot of time on and released to the public for free.
3) The source code is on this page. Feel free to contribute since it's "pretty basic"
4) Click on the player in your list you want to delete, then push the button on the far right to delete it.

Seems pretty..basic..
