### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by OthonGBR** [hunterjm/futgui#32]
Suggestion

It would be nice if it had a "price update" more efficient. One that only displays prices on the screen, or we we put somewhere the desired profit and it changes automatically adjusts the purchase price.
The AutoBuyer is great got to take 30K every day, just feel little unsure when activating Price Updater. But still congratulations on your work, this was only a suggestion.

Thanks

**Comment by hunterjm** [comment]
The profit can be derived by `(sold price * 0.95) - bought price`.  The settings below the checkbox are to configure how the auto update works.  If you buy at 90%, sell at 100% and set your BIN at 105%, you will have a profit between 5%-10%.  Sometimes less because we have to round our bidding, but EA doesn't have to round it's tax.

So, for example, if a player normally sells for 1,900, and you set Buy to 90%, we would try to buy for 1,710.  Obviously we can't do that, so we round it based on the increment value, at this point it's 100, so we determine price by doing some math to round it to the nearest increment:

`100 * round(1710/100)` = `100 * 17` = `1700`

We do the same thing for the BIN price, which would be 1995, still 100 increment:

`100 * round(1995/100)` = `100 * 20` = `2000`

So we would buy for 1700.  List for 1900, and set the BIN price to 2000.  Your profit would the be either `105` or `200` depending on if the card was purchased at the starting bid or the full price.

I hope that clears things up.  If there are no other concerns in a week or so, I'll close the issue.
