### ISSUE TITLE
Problem!! Help Me!!

### ISSUE THREAD

**Issue by Noobft9** [hunterjm/futgui#37]
InternalServerError: (500) for me, what's this? How can i fix it?

**Comment by OthonGBR** [comment]
Me also lives giving it. Sometimes time to relistar the player. Sometimes I'll see and Bug in my FUT. And when I buy always the player!

**Comment by aftershock9** [comment]
Generally when InternalServerError: (500) happens its for two reasons:
- You have been temporary banned. Go to the webapp and see if you are able to search the transfer market. If you receive an error message on the web app while doing the transfer market search, it means you have been temporary banned.
- Its unable to bid on the player due to unforeseen issue.

If you aren't experiencing either of these issues, please provide more context i.e. your log output / debug window output, what players you were using, settings etc. This will help hunter in investigating if there is an issue.

**Comment by Noobft9** [comment]
Thank you. Fixed it!
