### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by darfinx** [hunterjm/futgui#38]
Hello,
at the beginning congrats for your project. it is really good for helping people. I am not developer and i cant help for development. But if you accept i will be happy for many suggestions which re usefully. 

1- Consumables ; for pc platform. (PS4 PSN account) i cant use for consumables. I think it will be good drop down list for consumables for all kind of. (rare gold ,  rare, silver rare, silver... traning, postiion changers etc)

2- Set time for bidding : i may choose setting item's time. for example bidding rare gold contracts which's remaining time is  20 min. 
3- auto buyer :
4 auto price : if i send item to trade-pile, it can be analyses on the market.  and suggest a price for selling. 

again congrats your project.

**Comment by Faruk-S** [comment]
Auto price would be very useful.

**Comment by hunterjm** [comment]
1) This is not on the timeline currently.  Because there are so fewer consumables than players, if I released that feature to the 300+ people using this Auto Buyer, nobody would make a profit off of it anyway.

2) Right now it only bids on cards expiring within 5 minutes, we could make this a setting, but you would risk spending too much money on bidding, and not have enough to snipe if you do it this way.

3) It already is an auto buyer??

4) That's what the "Watch Player" button on the player list screen is for.  You can highlight a player in your list and click "Watch Player" to get a detailed analysis of the market.

**Comment by darfinx** [comment]
Thank you

**Comment by Slowfox83** [comment]
Hello,

I also have a couple of suggestions.
I'm experiencing that i'm being 'outplayed' by manual traders.

Suggestion 1:
Have a checkbox for automatically bid the max bid price.
I miss a lot of auctions because another buyer bids my maxprice before me.
Yes, i will not do any great bargains, but i'll win way more auctions and have more steady income.

Suggestion 2:
Dont know how hard this is to code, but i'm missing some statistics of my players used.
When I have been botting at night and see that i've earned approx 10-20k from my player list. I am not sure what players on my list that have generated that income. I need to manually look through the list and calculate who should stay on my list.

I would find it useful to have a possibility to save/load player lists - or perhaps a tickbox to mark a player as a [Favourite player] / [Big earner] etc. And when youre in the first screen when you select players for your list, you can drag players in from your favourites, rather than searching for them.

Very happy with the bot, works excellent! :)

-Slowfox-
