### ISSUE TITLE
InternalServerError:  (500)

### ISSUE THREAD

**Issue by efereti** [hunterjm/futgui#39]
Previously everything was fine, but for some time I have an error:
2015-12-18 23:04:44    InternalServerError:  (500)
2015-12-18 23:06:30    InternalServerError:  (500)
2015-12-18 23:07:05    InternalServerError:  (500)
2015-12-18 23:07:05    Too many errors. Will resume in 5 minutes...
2015-12-18 23:07:05    Stopped bidding...
Please help.

**Comment by aftershock9** [comment]
Generally when InternalServerError: (500) happens its for two reasons:
- You have been temporary banned. Go to the webapp and see if you are able to search the transfer market. If you receive an error message on the web app while doing the transfer market search, it means you have been temporary banned.
- Its unable to bid on the player due to unforeseen issue.

If you aren't experiencing either of these issues, please provide more context i.e. your log output / debug window output, what players you were using, settings etc. This will help hunter in investigating if there is an issue.

**Comment by Elf-1** [comment]
I'm having the same problem with the Internal Server Error (500). I checked the WebApp and I can access the transfer market, however when I bid on a player it always says "You have either been outbid or the item is no longer available. Your bid was not accepted." After that I don't see that anyone has bid a higher price or something.

**Comment by hunterjm** [comment]
You could also be banned from bidding, and/or listing players as well as searching for players.  Try doing all 3 in the web app.  If you can't do one of them, it's a ban.  Try again in 24 hours.

**Comment by darfinx** [comment]
Hi, i have same issue now. but i can do all (search,list,bid buy) via mobile app, webapp, and console except futgui. i will  wait 24 hours then i will try again.
