### ISSUE TITLE
zeroing out coins after first bid cycle

### ISSUE THREAD

**Issue by koolaidjones** [hunterjm/futgui#63]
Once I start bidding and the first cycle completes it zeros out my coins and will not buy anything. If I log out and then back in they return until I try to bid again.

**Comment by hunterjm** [comment]
Looks like an issue. Unfortunately I can't debug up to this point because I don't own the game.

That is, unless someone wants to provide me a testing account. It doesn't matter what platform. I just need something that has played enough games that the transfer market is unlocked with a throw away email address that I can use to get the access code.

**Comment by hunterjm** [comment]
Fixed in the latest release [v1.1.0](https://github.com/hunterjm/futgui/releases/tag/v1.1.0).
