### ISSUE TITLE
Too many errors watching trades.

### ISSUE THREAD

**Issue by ghost** [hunterjm/futgui#65]
I keep getting the above message and it logs me out, It is when i click watch player. I only have 1 in my list aswell.

**Comment by hunterjm** [comment]
Looks like an issue. Unfortunately I can't debug up to this point because I don't own the game.

That is, unless someone wants to provide me a testing account. It doesn't matter what platform. I just need something that has played enough games that the transfer market is unlocked with a throw away email address that I can use to get the access code.

**Comment by hunterjm** [comment]
Fixed in the latest release [v1.1.0](https://github.com/hunterjm/futgui/releases/tag/v1.1.0).

**Comment by hunterjm** [comment]
Fixed in the latest release [v1.1.0](https://github.com/hunterjm/futgui/releases/tag/v1.1.0).
