### ISSUE TITLE
Fatal Error - Fifa Autobuyer Returned -1

### ISSUE THREAD

**Issue by sgmexec** [hunterjm/futgui#8]
When I set bidding options and press start bidding, it calculates relevant prices then pop up box with above message appears

**Comment by hunterjm** [comment]
Yeah.  I've looked into this a little bit.  It's because the core fut library uses a `FileHandler` for it's logger, which apparently isn't supported in the `multiprocessing` module.

This is only an issue if you have the "debug" option checked on the login page.  I'll probably just remove that feature from the next release until I can figure out a more sustainable way of logging.

**Comment by hunterjm** [comment]
This instance of the error should be fixed now (removed option for Debug).  Another one has appeared to have cropped up though.  Closing this in lieu of the other.
